from sqlalchemy.orm import Session

from .models import CarListing


SAMPLE_CARS = [
    {
        "title": "2015 Toyota Avensis 1.8 Valvematic CVT Business Edition",
        "make": "Toyota",
        "model": "Avensis",
        "registration_number": "",
        "year": 2015,
        "price": 5795,
        "mileage": 89000,
        "fuel_type": "Petrol",
        "gearbox": "Automatic CVT",
        "engine": "1.8 Valvematic CVT",
        "trim": "Business Edition",
        "road_tax": 210,
        "insurance_group": 17,
        "service_history": "Full",
        "mot_notes": "Recent MOT with no advisories.",
        "listing_url": "",
        "seller_type": "Dealer",
        "comfort_score_manual": 8,
        "reliability_score_manual": 9,
        "gearbox_risk_manual": "Low",
        "notes": "Very sensible shortlist car for long ownership.",
    },
    {
        "title": "2013 Skoda Superb 2.0 TDI DSG Elegance",
        "make": "Skoda",
        "model": "Superb",
        "registration_number": "",
        "year": 2013,
        "price": 5250,
        "mileage": 108000,
        "fuel_type": "Diesel",
        "gearbox": "Automatic DSG",
        "engine": "2.0 TDI DSG",
        "trim": "Elegance",
        "road_tax": 180,
        "insurance_group": 24,
        "service_history": "Full",
        "mot_notes": "Advisory for tyre worn near legal limit. DSG service invoice present.",
        "listing_url": "",
        "seller_type": "Dealer",
        "comfort_score_manual": 9,
        "reliability_score_manual": 8,
        "gearbox_risk_manual": "Medium",
        "notes": "Strong option if DSG and cambelt history check out.",
    },
    {
        "title": "2012 Lexus CT 200h SE-L e-CVT",
        "make": "Lexus",
        "model": "CT 200h",
        "registration_number": "",
        "year": 2012,
        "price": 5995,
        "mileage": 97000,
        "fuel_type": "Hybrid",
        "gearbox": "Automatic e-CVT",
        "engine": "1.8 Hybrid e-CVT",
        "trim": "SE-L",
        "road_tax": 20,
        "insurance_group": 21,
        "service_history": "Full",
        "mot_notes": "Minor advisory for brake pads wearing thin.",
        "listing_url": "",
        "seller_type": "Dealer",
        "comfort_score_manual": 7,
        "reliability_score_manual": 10,
        "gearbox_risk_manual": "Low",
        "notes": "Cheap to run, but check wheel size and ride comfort.",
    },
    {
        "title": "2014 Volvo S60 D4 Geartronic SE Lux",
        "make": "Volvo",
        "model": "S60",
        "registration_number": "",
        "year": 2014,
        "price": 5600,
        "mileage": 121000,
        "fuel_type": "Diesel",
        "gearbox": "Automatic Geartronic",
        "engine": "D4 Geartronic",
        "trim": "SE Lux",
        "road_tax": 150,
        "insurance_group": 27,
        "service_history": "Partial",
        "mot_notes": "Advisory for ball joint dust cover and minor exhaust leak.",
        "listing_url": "",
        "seller_type": "Private",
        "comfort_score_manual": 8,
        "reliability_score_manual": 7,
        "gearbox_risk_manual": "Medium",
        "notes": "Great seats, but history needs checking carefully.",
    },
    {
        "title": "2013 Audi A6 2.0 TDI Multitronic S line",
        "make": "Audi",
        "model": "A6",
        "registration_number": "",
        "year": 2013,
        "price": 5850,
        "mileage": 126000,
        "fuel_type": "Diesel",
        "gearbox": "Automatic Multitronic",
        "engine": "2.0 TDI Multitronic",
        "trim": "S line",
        "road_tax": 180,
        "insurance_group": 31,
        "service_history": "Unknown",
        "mot_notes": "Advisory mentions suspension arm corrosion and oil leak.",
        "listing_url": "",
        "seller_type": "Dealer",
        "comfort_score_manual": 6,
        "reliability_score_manual": 4,
        "gearbox_risk_manual": "High",
        "notes": "Looks tempting, but this is exactly the sort of risky luxury bargain to treat carefully.",
    },
    {
        "title": "2012 Mercedes-Benz E-Class E220 CDI automatic Avantgarde",
        "make": "Mercedes-Benz",
        "model": "E-Class",
        "registration_number": "",
        "year": 2012,
        "price": 6500,
        "mileage": 144500,
        "fuel_type": "Diesel",
        "gearbox": "Automatic",
        "engine": "E220 CDI automatic",
        "trim": "Avantgarde",
        "road_tax": 300,
        "insurance_group": 34,
        "service_history": "Partial",
        "mot_notes": "Previous MOT mentions corrosion, brake pipe corroded and emissions.",
        "listing_url": "",
        "seller_type": "Private",
        "comfort_score_manual": 10,
        "reliability_score_manual": 6,
        "gearbox_risk_manual": "Medium",
        "notes": "Comfortable but fails budget, tax and mileage targets.",
    },
]


def seed_database(db: Session) -> None:
    existing = db.query(CarListing).count()
    if existing:
        return

    db.add_all(CarListing(**car) for car in SAMPLE_CARS)
    db.commit()
